# Generated by Django 5.1.2 on 2024-10-27 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название места')),
                ('salary', models.CharField(max_length=100, verbose_name='Стоимость')),
                ('weather', models.CharField(max_length=255, verbose_name='Для какого времени года')),
                ('descriprion', models.TextField(verbose_name='Об этом месте')),
                ('owner', models.CharField(max_length=255, verbose_name='Кто рекомендует')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес места')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure_app.category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
