# Generated by Django 5.1.2 on 2024-10-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_app', '0004_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={},
        ),
    ]
