# Generated by Django 5.1.2 on 2024-10-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_app', '0005_alter_home_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
