# Generated by Django 5.1.2 on 2024-10-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_app', '0007_concert_kino_musems_parks_sport_delete_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kino',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название места'),
        ),
    ]
