# Generated by Django 5.1.2 on 2024-10-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_app', '0021_alter_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ivents',
        ),
    ]
