# Generated by Django 5.1.2 on 2024-10-30 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_app', '0025_alter_musems_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Запись')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации')),
            ],
        ),
        migrations.AlterField(
            model_name='kino',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название места'),
        ),
    ]
