# Generated by Django 5.1.2 on 2024-10-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_app', '0026_zapis_alter_kino_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zapis',
            options={'verbose_name': 'Кино', 'verbose_name_plural': 'Кино'},
        ),
    ]
