# Generated by Django 5.1.2 on 2024-11-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_app', '0029_rename_musems_place_remove_kino_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='descriprion',
            new_name='description',
        ),
    ]
